.github/workflows/dev-build-deploy.yaml

Fixed Github Secret name in workflow.yaml

---

Dockerfile

Changed env vars in Dockerfile to point @ CloudRun

---

.github/workflows/dev-build-deploy.yaml
Dockerfile

Reverting API URLs for demo

---

.github/workflows/dev-build-deploy.yaml

More reverting

---

components/Pois/_nav.scss
components/explorer/Aladin/utilities.js
components/explorer/Controls/Filters/_styles.scss
components/explorer/Controls/Search/_styles.scss
components/explorer/Controls/Zoom/_styles.scss
components/explorer/Controls/_styles.scss
components/explorer/Controls/index.jsx
components/explorer/SourceDetails/index.js
components/guidedExperiences/GuidedExperienceLanding.js
components/guidedExperiences/GuidedExperienceListItem.js
components/layouts/Aladin/index.js
components/tours/Intro.js
components/tours/ListItem.js
pages/_document.js
theme/styles/abstracts/mixins/_appearance.scss
theme/tokens.json

Includes mishmash of other minor improvements including support for updated img paths from Craft

[EPO-5208] Better JQuery loading solution

---

components/explorer/SourceDetails/index.js
lib/api/astroObject.js
lib/api/fragments/astroObject.js

[EPO-5557] Update graphQL astroDB stuff to comply with changes to the API

---

.github/workflows/dev-build-deploy.yaml
.github/workflows/dev-pull-request.yaml
.github/workflows/master-pr.yaml
.github/workflows/master-push.yaml

Added workflow files

---

.github/workflows/gae-master-with-preview.yaml
.github/workflows/gae-master.yaml

Renamed `main` to `master` in `int` workflow

Renamed `main` to `master` in `int` worfklow

---

.github/workflows/build-and-push.yaml

Fix version number. Typo in last PR.

fix gcp version

---

package.json
yarn.lock

build(dep): update next

---

app/api/revalidate/route.ts
lib/api/urql.ts
lib/i18n/index.ts
next-env.d.ts

feat: revalidation

---

.github/workflows/gae-master-with-preview.yaml
.github/workflows/gae-master.yaml

Updated workflow for new primary branch name

Updated workflow for new primary branch name

---

.github/workflows/build-and-push.yaml

Swap `.api` in workflow with `.client`

Swap `.api` in workflow with `.client`

---

.github/workflows/gae-develop-with-preview.yaml
.github/workflows/gae-develop.yaml
.github/workflows/gae-master-with-preview.yaml
.github/workflows/gae-master.yaml
.github/workflows/gae-release-tag.yaml

Add build args for app engine workflows to fix failing workflow builds
RUN_BUILD=false

Update run build build arg for app engine workflow

---

.github/workflows/build-and-push.yaml
.github/workflows/gae-develop-with-preview.yaml
.github/workflows/gae-develop.yaml
.github/workflows/gae-master-with-preview.yaml
.github/workflows/gae-master.yaml
.github/workflows/gae-release-tag.yaml

Add build arg RUN_BUILD= true to all app engine workflows

Fix App Engine Workflows

---

app/[locale]/explorer/page.tsx
components/organisms/CurrentPositionPopover/index.tsx
components/organisms/CurrentPositionPopover/styles.module.css
lib/aladin/astro.ts
lib/aladin/helpers.ts
lib/i18n/localeStrings/en/translation.json
package.json

Right click to show coordinates, wait on `aladin-lite` update with necessary changes for right-click events.
Resolves #173, #191

feat: right click to show coordinates

---

Dockerfile
app/api/revalidate/route.ts
codegen.ts
components/molecules/ExplorerControls/Share/index.tsx
components/pages/TourSummary/index.tsx
env.config.js
env.ts
lib/fetch.js
next.config.js
package.json
services/api/client.ts
yarn.lock

build: set up type-safe environment

---

app/[locale]/explorer/page.tsx
components/molecules/ExplorerControls/index.tsx
gql/gql.ts
gql/graphql.ts
services/api/explorer.ts

refactor: remove inactive features

---

app/[locale]/embed/page.tsx

feat: right click added to embeds

---

components/organisms/Listener/parameters.js
components/organisms/Listener/utilities.js

Updated the automatic walk mode to stay at the same speed regardless of zoom level

Update to automatic mode

---

components/organisms/Listener/parameters.js
components/organisms/Listener/sketch.jsx
components/organisms/Listener/utilities.js

Added the ability to use the arrow keys to control movement in the sonification app

feat: added keyboard controls to sonification

---

components/molecules/SonificationControls/OrientedSlider/index.tsx
components/organisms/Listener/PixelSynth.js
components/organisms/Listener/sketch.jsx

- fixed slider not working correctly on mobile
- fixed audio context setup so it's more mobile friendly

fix: sonification controls and audio context setup

---

components/organisms/Listener/sketch.jsx

- Added a fix to resize P5 if Aladin changes size

fix: p5 resizing issue

---

components/organisms/CurrentPositionPopover/index.tsx
hooks/useAladinContextMenu.ts
types/aladin-events.d.ts

feat: long press for context menu

---

components/organisms/Aladin/styles.module.css

feat: add back aladin logo
